In [1]:
import numpy as np

In [3]:
# Step 1: Creating random vector of size 15 with integers in range 1–20
arr = np.random.randint(1, 21, size=15)
print("Original Array:\n", arr)


Original Array:
 [ 8  2 19  3 12 12 20 19 12 18 17 20 16 18 10]


In [4]:
# Step 2: Reshape the array to 3x5
arr = arr.reshape(3, 5)
print("\nReshaped Array (3x5):\n", arr)


Reshaped Array (3x5):
 [[ 8  2 19  3 12]
 [12 20 19 12 18]
 [17 20 16 18 10]]


In [5]:
# Step 3: Print array shape
print("\nShape of the array:", arr.shape)


Shape of the array: (3, 5)


In [6]:
# Step 4: Replace the max in each row with 0
for i in range(arr.shape[0]):
    max_index = np.argmax(arr[i])
    arr[i, max_index] = 0

print("\nModified Array (Max in each row replaced by 0):\n", arr)


Modified Array (Max in each row replaced by 0):
 [[ 8  2  0  3 12]
 [12  0 19 12 18]
 [17  0 16 18 10]]


In [7]:
#1b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
#type of the array.

# Create a 4x3 array with 4-byte integers (int32)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)

# Print the array
print("Array:\n", arr)

# Print shape of the array
print("\nShape:", arr.shape)

# Print type of the array object
print("Type:", type(arr))

# Print data type of the elements
print("Data type:", arr.dtype)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [9]:
#c. Write a program to compute the eigenvalues and right eigenvectors of a given square array(A) given below:

# Define the square matrix
A = np.array([[3, -2],
              [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("Right Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [12]:
#d.Compute the sum of the diagonal element of a given array(arr).
# Define the array
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Compute the sum of diagonal elements
diag_sum = np.trace(arr)

print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [13]:
#E.Write a NumPy program to create a new shape to an array(arr) without changing its data.
# Original array (3x2)
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

# Reshape to (2x3)
reshaped_arr = arr.reshape(2, 3)

print("Original (3x2):\n", arr)
print("\nReshaped (2x3):\n", reshaped_arr)


Original (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]
